export const SITE = {
  meta: {
    title: 'ROOCKY.DEV',
    description: 'Portfolio of Ahmed Ghaithan — creative developer building web, games, and AI tools from Malaysia.',
    url: 'https://roocky.dev',
    ogTitle: 'Roocky | Developer Portfolio',
  },
  personal: {
    name: 'AHMED HUSAM GHAITHAN',
    alias: 'ROOCKY.DEV',
    role: 'Creative Thinker & Tech Enthusiast',
    location: 'KUALA LUMPUR, MY',
    tz: 'Asia/Kuala_Lumpur',
    tzLabel: 'UTC+8',
    email: 'letsbuild@roocky.dev',
    bio: 'Self-taught, curious, and stubborn about craft. I split my time between cybersecurity coursework at UNITEN and a rotating bench of side projects — Minecraft mods, web platforms, and AI-assisted tooling. I prefer shipping small, sharp things over shipping big, fuzzy ones.',
    heroParagraph: 'Crafting immersive digital experiences; bridging the gap between imagination and reality. Minecraft mods, web platforms, AI pipelines. Quiet, obsessive, 24/7.',
    socials: {
      github: 'https://github.com/ROOCKY-dev/',
      instagram: 'https://www.instagram.com/roocky_dev/',
      wa: 'https://wa.link/jpl25x',
    },
  },
  roles: ['VIBECODER', 'STUDENT', 'GAMER', 'MODDER'] as const,
  marquee: [
    '1+ YEARS EXP',
    '2 SHIPPED PROJECTS',
    'AI / VIBECODING',
    'CYBER SEC @ UNITEN',
    'AVAILABLE FOR COLLAB',
    'REMOTE FRIENDLY',
    'BASED IN MALAYSIA',
  ],
  stats: [
    { value: '02', label: 'Projects Shipped', detail: 'MC mods · web · AI' },
    { value: '01+', label: 'Years Shipping', detail: 'Full-stack + gamedev' },
    { value: 'MY', label: 'Kuala Lumpur', detail: 'Remote-friendly' },
  ],
  capabilities: [
    {
      id: 'ai',
      number: '01',
      title: 'AI & Automation',
      verb: 'Ship AI-driven apps',
      description: 'Integrating LLMs into production workflows, from automated content pipelines to intelligent coding agents that ship faster than traditional teams.',
      tools: ['Claude Code', 'Cursor', 'Antigravity', 'Ollama', 'OpenAI'],
    },
    {
      id: 'game',
      number: '02',
      title: 'Game & Mods',
      verb: 'Make worlds & mods',
      description: 'Crafting complex mechanics and immersive environments. Specializing in Java-based modding for Minecraft and C# systems within Unity.',
      tools: ['Java', 'NeoForge', 'Fabric', 'C#', 'Unity', 'Blender'],
    },
    {
      id: 'web',
      number: '03',
      title: 'Web Development',
      verb: 'Ship fast websites',
      description: 'Developing high-performance, accessible, and visually striking web experiences using the latest React ecosystem.',
      tools: ['TypeScript', 'Next.js', 'React 19', 'Tailwind', 'Framer Motion'],
    },
    {
      id: 'ops',
      number: '04',
      title: 'DevOps & Infra',
      verb: 'Keep servers on',
      description: 'Managing robust server environments and deployment pipelines to ensure maximum uptime and security for 24/7 digital products.',
      tools: ['Linux', 'Ubuntu', 'Docker', 'Git', 'C++'],
    },
  ],
  projects: [
    {
      id: 'stackerforge',
      number: '01',
      title: 'STACKERFORGE',
      category: 'MC MOD DEVELOPMENT',
      year: '2024',
      description: 'An experiment in developing MC mods using AI that went better than expected. Used Google AntiGravity and OpenAI image-gen to ship the final product.',
      longDescription: 'StackerForge began as a curiosity-driven experiment — could AI meaningfully assist in Minecraft mod development? The answer turned out to be a resounding yes. Leveraging Google AntiGravity for code generation and OpenAI for textures and assets, the mod went from concept to a fully playable release in record time.',
      tags: ['Minecraft', 'AI', 'Modding', 'Java'],
      role: 'Lead Developer',
      stack: ['Java', 'NeoForge', 'Google AntiGravity', 'OpenAI'],
      link: 'https://modrinth.com/mod/stackerforge',
      featured: true,
      gradient: ['#0A0A0A', '#8A6A3A'],
      glyph: 'SF',
      tagline: 'Blocks that stack themselves.',
    },
    {
      id: 'portfolio-v4',
      number: '02',
      title: 'PORTFOLIO V4',
      category: 'WEB DEVELOPMENT',
      year: '2026',
      description: "Swiss / Bauhaus high-performance portfolio — the very site you're browsing. Built with Next.js 16, React 19, Framer Motion.",
      longDescription: 'Version 4 of the personal portfolio. Kinetic workshop feel, thick rules, typographic cards, live status. Built on Next.js 16 with React 19; data-driven sections make content updates painless.',
      tags: ['Next.js', 'React', 'Framer Motion', 'Tailwind', 'AI'],
      role: 'Designer & Developer',
      stack: ['Next.js', 'React 19', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
      link: 'https://roocky.dev',
      featured: true,
      gradient: ['#0A0A0A', '#3A4A6A'],
      glyph: 'P4',
      tagline: 'This site. Recursion intentional.',
    },
    {
      id: 'anvil',
      number: '03',
      title: 'ANVIL',
      category: 'PRIVATE TOOLING',
      year: '2026',
      description: 'Private workshop tooling project. Details under wraps for now.',
      longDescription: 'Anvil is a private tooling project — a workshop companion that keeps recurring jobs running quietly in the background. Writeup coming once it ships publicly.',
      tags: ['Tooling', 'Workshop'],
      role: 'Author',
      stack: ['TypeScript', 'Node', 'TBD'],
      status: 'IN PROGRESS' as const,
      gradient: ['#0A0A0A', '#4A4A4A'],
      glyph: 'AN',
      tagline: 'Quiet workshop companion.',
    },
    {
      id: 'r-focus',
      number: '04',
      title: 'R-FOCUS',
      category: 'PRODUCTIVITY',
      year: '2026',
      description: 'AI-powered Pomodoro focus timer with Claude-generated plans, streaks, and analytics.',
      longDescription: 'R-Focus is a Pomodoro timer that plans your session with an LLM before you start — break down a task, estimate tomatoes, execute. Streak + analytics keep the feedback loop tight.',
      tags: ['AI', 'Productivity', 'React'],
      role: 'Author',
      stack: ['React', 'Claude', 'Local-first'],
      status: 'IN PROGRESS' as const,
      gradient: ['#0A0A0A', '#6A4A6A'],
      glyph: 'RF',
      tagline: 'Plan. Focus. Ship.',
    },
  ],
  services: [
    { number: '01', title: 'Minecraft Mod', description: 'Custom NeoForge / Fabric mods, from mechanic to release on Modrinth.', price: 'FROM $300', timeline: '2–4 WEEKS' },
    { number: '02', title: 'Web Build', description: 'Marketing sites, portfolios, dashboards. Next.js, opinionated type, honest motion.', price: 'FROM $800', timeline: '2–3 WEEKS' },
    { number: '03', title: 'AI Pipeline', description: 'Practical vibecoding setups: Cursor / Claude / Ollama, codegen & content.', price: 'FROM $400', timeline: '1–2 WEEKS' },
  ],
  stack: {
    LANGUAGES: ['C++', 'Java', 'C#', 'TypeScript'],
    FRAMEWORKS: ['Next.js', 'React 19', 'Tailwind', 'NeoForge', 'Fabric'],
    'GAME ENGINES': ['Unity'],
    INFRASTRUCTURE: ['Linux', 'Ubuntu', 'Docker'],
    TOOLS: ['Git', 'Blender', 'OpenAI', 'AntiGravity', 'Cursor', 'Claude Code', 'Ollama'],
  },
  status: {
    current: 'WORKING' as const,
    states: {
      WORKING: { label: 'WORKING', description: 'Redesigning the portfolio — Swiss/Bauhaus style.' },
      AVAILABLE: { label: 'AVAILABLE', description: 'Open to new collaborations — mods, webs, AI pipelines.' },
      STUDYING: { label: 'STUDYING', description: 'Cyber Security coursework @ UNITEN — networks week.' },
      RESTING: { label: 'RESTING', description: 'Offline. Back on the tools in a bit.' },
    },
  },
  tags: ['Malaysia, MY', 'Cyber Sec @ UNITEN', 'Open for collab', 'Speaks EN / AR'],
  log: [
    { time: '04:12', event: 'git push  portfolio-v4  origin/production' },
    { time: '03:58', event: 'refactor  Hero  →  kinetic cycling roles' },
    { time: '03:31', event: 'drop  Three.js  from bundle  (-214 KB)' },
    { time: '02:47', event: 'add  WorkshopStatus  component' },
    { time: '02:12', event: 'coffee  ++' },
    { time: '01:40', event: 'plan   →   spec/2026-04-06-portfolio.md' },
  ],
} as const;

export type Project = (typeof SITE)['projects'][number];
export type Capability = (typeof SITE)['capabilities'][number];
export type Service = (typeof SITE)['services'][number];
