import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from '@/components/ui/ToastSystem';
import SmoothScroll from '@/components/ui/SmoothScroll';
import CursorTrail from '@/components/ui/CursorTrail';
import NoiseOverlay from '@/components/ui/NoiseOverlay';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout
 *
 * Defines the global structure of the application.
 * - Sets up fonts (Geist).
 * - Applies global CSS variables and styles.
 * - Wraps the app with global providers:
 *   - ToastProvider: For notification toasts.
 *   - SmoothScroll: For smooth scrolling behavior (Lenis).
 *   - CursorTrail: For the custom mouse trail effect.
 *   - NoiseOverlay: For the cinematic film grain effect.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <NoiseOverlay />
        <SmoothScroll />
        <CursorTrail />
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
